graphhopper:
    datareader.file: /data/source/region.osm.pbf
    graph.location: /data/graph-cache

    profiles:
        - name: foot
          custom_model_files: [foot.json, foot_elevation.json]
    profiles_ch: []
    profiles_lm:
        - profile: foot

    graph.encoded_values: >-
        foot_access,foot_average_speed,road_class,road_class_link,road_environment,
        road_access,surface,smoothness,track_type,hike_rating,mtb_rating,osm_way_id,
        foot_temporal_access,average_slope,max_slope,foot_priority

    graph.elevation.provider: srtm
    graph.elevation.cache_dir: /data/srtm
    graph.elevation.interpolate: bilinear
    graph.elevation.long_edge_sampling_distance: 30
    graph.elevation.way_point_max_distance: 5

    prepare.min_network_size: 50
    prepare.subnetworks.threads: 1
    routing.max_visited_nodes: 1000000
    routing.timeout_ms: 15000
    routing.non_ch.max_waypoint_distance: 50000
    import.osm.ignored_highways: motorway,trunk
    graph.dataaccess.default_type: MMAP

server:
    application_connectors:
        - type: http
          port: 8989
          bind_host: 0.0.0.0
          max_request_header_size: 50k
    admin_connectors:
        - type: http
          port: 8990
          bind_host: 0.0.0.0
    request_log:
        appenders: []

logging:
    level: INFO
    appenders:
        - type: console
          time_zone: UTC
